### ISSUE TITLE
Chore/Feat: Reset & Document `@home` Wifi Network

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-computer-networking#14]
I've [procrastinated](https://github.com/nelsonic/nelsonic.github.io/issues/849#issuecomment-1206325136) on this task for _months_ because: 

1. resetting the network requires a decent chunk of time; probably a couple of hours, but unknown! 🤷‍♂️ 
2. setting up and testing the `new` additions to the network (2 new cameras, a doorbell and wifi access point) requires a decent amount of configuration ... ⏳ 
3. I can only do this when nobody is _using_ the network i.e. not on a week/work day 🧑‍💻 
4. we've been away from @home most weekends the past few months due to family illness or visits ... 👨‍👧‍👦 
5. there's always _something_ `else` to do ... 🙄 

# Related issues: 

+ [ ] Wifi Quality Issues: https://github.com/dwyl/home/issues/222
+ [ ] Outdoor Wireless Access Point: https://github.com/dwyl/home/issues/207
+ [ ] Doorbell: https://github.com/dwyl/home/issues/201 
+ [ ] Video: https://github.com/dwyl/home/issues/169 & https://github.com/dwyl/home/issues/130
+ [ ] UPS: https://github.com/dwyl/home/issues/167
+ [ ] Pi Hole: https://github.com/dwyl/learn-computer-networking/issues/10 

I expect this to take around `T4h` including reset, re-configuring/adopting, testing and documenting
During that time the `@home` WiFi network will be unavailable for about `T1h`.
At the very least we will will resolve the intermittent WiFi issues.

# Todo

+ [ ] Login to the Ubiquiti Network using MacBook that has the agents running on it.
+ [ ] Document the "As is" as much as possible ***`before`*** performing the reset.
+ [ ] Setup from Scratch!

# Stretch Goals

+ [ ] Setup UPS next to the main switch
+ [ ] Disassemble wall-mount so that we can tidy it up!
+ [ ] Setup place for Pi Hole https://github.com/dwyl/learn-computer-networking/issues/10

**Comment by nelsonic** [comment]
This is the current network "hub":

![image](https://user-images.githubusercontent.com/194400/233786444-00f525b4-6b4d-4d9e-ad1d-d76e74dd24e2.jpeg)

The ISP router, Ubiqiti USG & Switch are all just mounted to a plywood board on the wall:

![image](https://user-images.githubusercontent.com/194400/233786506-4f8f18ab-1f58-4728-97ad-b98d9d06e5e8.jpeg)

It's not pretty. But it's functional and allowed us to put the gear *somewhere*. 
I'm going to reconfigure it and add a few more components. 
This is just documenting the "As is" from a physical hardware perspective. 👌

**Comment by nelsonic** [comment]
Firstly, going to add this inline UPS that will ensure the Security Systems have **12h** of power in the event of a power cut/failure:

![image](https://user-images.githubusercontent.com/194400/233787051-a483c7f3-f425-4602-bede-fdc7abca0566.jpeg)

**Comment by nelsonic** [comment]
Current topology:

<img width="1329" alt="Screen Shot 2023-04-22 at 14 40 34" src="https://user-images.githubusercontent.com/194400/233788617-7221dcbe-bb9a-49e0-ba29-eff3574a3d17.png">

Only two of the Access Points (out of 5) are working...
We have our darling toddler to thank for this.
And our own naiveté at putting the Access points at his level ...
i.e. by placing the RJ45 ports within reach of children, 
we practically _guarantee_ that they will mess with the APs. 🙄 

Going to see if the APs are recoverable.
Or if I just have to do a full reset. 🔍

**Comment by nelsonic** [comment]
The Unifi 16 Port PoE Switch only has 4 ports active:
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/194400/233789066-d4d772a7-cfea-4bfe-b9be-32c41ad1b2e2.png">

**Comment by nelsonic** [comment]
Trying to see if we can re-adopt the `DiningRoom` AP:
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/194400/233821664-0fa48ad0-4d21-4a2f-9078-73a9ab35ee2b.png">

Both `Locate Device` and `Restart Device` are unavailable. I suspect it's been disconnected and then incorrectly replaced ... 
<img width="1295" alt="home-network-dining-room-unavailable" src="https://user-images.githubusercontent.com/194400/233821755-37bcaf22-6f50-4867-84b1-fdb61c171787.png">

**Comment by nelsonic** [comment]
These are the CAT6 cables connected to the switch:

![IMG_3646](https://user-images.githubusercontent.com/194400/233825752-3ff51e0c-a867-4560-b048-ca2a7a9bcbd3.jpeg)

removed everything from the wall mount to start from scratch with the layout:

![IMG_3648](https://user-images.githubusercontent.com/194400/233825788-78e4451b-4bb6-4d09-ab00-f693ccac2c54.jpeg)

reconnected the ISP router / AP so that we still have *some* internet in the house … 🛜 

![IMG_3651](https://user-images.githubusercontent.com/194400/233825830-73a32b3e-fb98-4975-a392-10bc671d7b33.jpeg)

moved it to the top-left to make space for the rest of the gear.

then got interrupted so need to return to the rest of the setup later … 💭

**Comment by nelsonic** [comment]
The **UniFi Devices** page: https://localhost:8443/manage/default/devices gives a good overview:
<img width="1590" alt="home-net-default-devices" src="https://user-images.githubusercontent.com/194400/233822155-6655544f-90cd-4ec9-9b80-2a6d497fd2c0.png">

Attempting to adopt the `U6-Mesh`:
<img width="1326" alt="home-net-u6-mesh-adopt" src="https://user-images.githubusercontent.com/194400/233822202-d184459e-ef1f-4d37-af35-c8abcb495d47.png">

adopting ...
<img width="1326" alt="home-net-u6-mesh-adopting" src="https://user-images.githubusercontent.com/194400/233822221-d0a97327-fe3a-4063-9d5f-06a02d7b31f6.png">
