### ISSUE TITLE
Chore: Move `CloudKey+` and `PiHole` to Secure(ish) Closet with `UPS` 🔒 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-computer-networking#20]
At present the [`CloudKey+`](https://eu.store.ui.com/eu/en/pro/category/all-cameras-nvrs/products/unifi-cloudkey-plus) that runs the security cameras sits next to the Switch in the workshop. That's "fine" in the scenario that we _trust_ everyone that enters the workshop ... but recently the Workshop (external door) has been left open and UPS/DHL delivery people have entered the workshop without anyone present ... 😕 i.e. unsupervised entry!!

I _definitely_ don't trust delivery people to enter our property unsupervised. 
If the recording device for the security cameras is visible to the "intruder",
i.e. they can just unplug or remove the video recorder, then the whole security system is worthless.

So ...

# Todo

Assemble the pieces:
+ [x] Power Strip (with light switch) for connecting non-essential items to mains
+ [x] Second extension (no light) for connecting the components to the UPS. 

+ [x] Build mounting bracket for:
  + [x] `UPS`
  + [x] `Switch`
  + [x] `CloudKey+`
+ [x] Mount to Wall
+ [x] Connect with Cables
+ [x] Connect Network Cable to `Switch` and `CloudKey+`
+ [x] Route + Connect Network Cable between `Switch` and `PiHole`

@iteles I've ordered another `Switch` as there is only one Network terminal in the closet. Invoice uploaded to Google Drive. 📁 
Only going to _start_ working on this when the `Switch` arrives. ⏳ (usually around 2 days from placing the order...)

**Comment by nelsonic** [comment]
devices all mounted to custom made board with cable tidy (except the yellow one while I was testing/replacing it…) 

![IMG_7499](https://github.com/dwyl/learn-computer-networking/assets/194400/2e53c060-e7ff-43a8-aa76-dc24b2569eec)

everything operational. Tested switching off the power and the UPS works seamlessly:

https://github.com/dwyl/learn-computer-networking/assets/194400/b87feff9-9bdf-4ed9-a63d-48fb83789e81

But just FYI: everything is working. 👌

**Comment by nelsonic** [comment]
Not much for you to review. But you can open the Protect App on your phone and confirm that all Cameras & Recordings are working as expected. 👌

**Comment by nelsonic** [comment]
Happy this is working as expected. ✅ 
Been able to receive Doorbell notification on my phone remotely while away from home. 🔔 
Closing. 👍
